---
version: '3.5'
services:

  broker:
    volumes:
        - ../../other/connect-override-policy-sftp-source/client.properties:/tmp/client.properties
    environment:
      KAFKA_AUTHORIZER_CLASS_NAME: $KAFKA_AUTHORIZER_CLASS_NAME
      KAFKA_ZOOKEEPER_SET_ACL: "true"
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "false"
      KAFKA_LOG4J_LOGGERS: "kafka.authorizer.logger=INFO"
      KAFKA_SUPER_USERS: User:broker;User:schemaregistry;User:client;User:connect

  schema-registry:
    volumes:
        - ../../other/connect-override-policy-sftp-source/client.properties:/tmp/client.properties

  # getting weird "Couldn't create directory: Failure", so created image from this PR https://github.com/atmoz/sftp/pull/164
  # https://github.com/amaysim-au/docker-sftp/tree/chroot-user
  # docker build -t vdesabou/sftp .
  # docker push vdesabou/sftp
  sftp-server:
    image: vdesabou/sftp
    hostname: sftp-server
    container_name: sftp-server
    ports:
      - "2222:22"
    command: foo:pass:::upload

  connect:
    volumes:
        - ../../other/connect-override-policy-sftp-source/client.properties:/tmp/client.properties
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-sftp
      CONNECT_CONNECTOR_CLIENT_CONFIG_OVERRIDE_POLICY: Principal