---
version: '3.5'
services:

  connect:
    volumes:
      - ../../ksqldb/benchmarking-scenarios/schemas:/tmp/schemas
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-datagen