---
version: '3.5'
services:

  connect:
    volumes:
      - ../../ksqldb/benchmarking-scenarios/schemas:/tmp/schemas
      - ../../environment/rbac-sasl-plain/scripts/security/client_sasl_plain.config:/etc/kafka/secrets/client_sasl_plain.config
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-datagen