---
version: '3.5'
services:
  # connect-us is used to launch mirrormaker 2 executable
  connect-us:
    volumes:
        - ../../multi-data-center/mirrormaker2/connect-mirror-maker.properties:/etc/kafka/connect-mirror-maker.properties
        - ../../multi-data-center/mirrormaker2/connect-log4j.properties:/tmp/connect-log4j.properties
    environment:
      KAFKA_LOG4J_OPTS: "-Dlog4j.configuration=file:/tmp/connect-log4j.properties"