version: '3.5'
services:

  bind:
    build:
      context: ../../other/ldap-authorizer-with-ldap-failover/bind
      args:
        DOMAIN_FILE: "confluent.io-ldap"
    hostname: bind.confluent.io
    container_name: bind
    restart: unless-stopped
    depends_on:
    - ldap
    - ldap2
    - ldap3
    networks:
      testing_net:
        ipv4_address: 172.28.1.1

  ldap:
    hostname: ldap.confluent.io
    networks:
      testing_net:
        ipv4_address: 172.28.1.2

  ldap2:
    image: osixia/openldap:1.3.0
    hostname: ldap2.confluent.io
    container_name: ldap2
    environment:
      LDAP_ORGANISATION: "Confluent"
      LDAP_DOMAIN: "confluent.io"
    volumes:
      - ../../environment/ldap-authorizer-sasl-plain/ldap/custom:/container/service/slapd/assets/config/bootstrap/ldif/custom
    command: "--copy-service"
    networks:
      testing_net:
        ipv4_address: 172.28.1.3


  ldap3:
    image: osixia/openldap:1.3.0
    hostname: ldap3
    container_name: ldap3
    environment:
      LDAP_ORGANISATION: "Confluent"
      LDAP_DOMAIN: "confluent.io"
    volumes:
      - ../../environment/ldap-authorizer-sasl-plain/ldap/custom:/container/service/slapd/assets/config/bootstrap/ldif/custom
    command: "--copy-service"
    networks:
      testing_net:
        ipv4_address: 172.28.1.4

  zookeeper:
    hostname: zookeeper.confluent.io
    networks:
      testing_net:
        ipv4_address: 172.28.1.5

  broker:
    hostname: broker.confluent.io
    # this is not working so workaround with /etc/resolv.conf
    dns: 172.28.1.1
    dns_search: confluent.io
    volumes:
      - ../../other/ldap-authorizer-with-ldap-failover/resolv.conf:/etc/resolv.conf
    environment:
      # https://ldap.com/dns-srv-records-for-ldap/
      # LDAP provider URL
      KAFKA_LDAP_JAVA_NAMING_PROVIDER_URL: "ldap:///dc=confluent,dc=io"
      KAFKA_LDAP_GROUP_SEARCH_BASE: ou=groups
    networks:
      testing_net:
        ipv4_address: 172.28.1.6

  schema-registry:
    hostname: schema-registry.confluent.io
    networks:
      testing_net:
        ipv4_address: 172.28.1.7


  connect:
    # this is not working so workaround with /etc/resolv.conf
    dns: 172.28.1.1
    dns_search: confluent.io
    volumes:
      - ../../other/ldap-authorizer-with-ldap-failover/resolv.conf:/etc/resolv.conf
    hostname: connect.confluent.io
    depends_on:
    - ldap
    - ldap2
    - ldap3
    - bind
    networks:
      testing_net:
        ipv4_address: 172.28.1.8

  control-center:
    hostname: control-center.confluent.io
    networks:
      testing_net:
        ipv4_address: 172.28.1.9

networks:
  default:
    name: confluent.io
  testing_net:
    ipam:
        driver: default
        config:
        - subnet: 172.28.0.0/16