version: '3.5'
services:

  bind:
    build:
      context: ../../other/ldap-authorizer-with-ldap-failover/bind
      args:
        DOMAIN_FILE: "confluent.io-ldaps"
    hostname: bind.confluent.io
    container_name: bind
    ports:
    - 53:53/udp
    restart: unless-stopped
    depends_on:
    - ldap
    - ldap2
    - ldap3
    networks:
      testing_net:
        ipv4_address: 172.28.1.1

  ldap:
    hostname: ldap.confluent.io
    networks:
      testing_net:
        ipv4_address: 172.28.1.2
    environment:
      LDAP_TLS_CRT_FILENAME: ldap-ca1-signed.crt
      LDAP_TLS_KEY_FILENAME: ldap.key
      LDAP_TLS_CA_CRT_FILENAME: snakeoil-ca-1.crt
      LDAP_TLS_VERIFY_CLIENT: "try"
    volumes:
      - ../../environment/ldap-authorizer-sasl-plain/ldap/custom:/container/service/slapd/assets/config/bootstrap/ldif/custom
      - ../../other/ldap-authorizer-with-ldap-failover/security:/container/service/slapd/assets/certs

  ldap2:
    image: osixia/openldap:1.3.0
    hostname: ldap2.confluent.io
    container_name: ldap2
    environment:
      LDAP_ORGANISATION: "Confluent"
      LDAP_DOMAIN: "confluent.io"
      LDAP_TLS_CRT_FILENAME: ldap2-ca1-signed.crt
      LDAP_TLS_KEY_FILENAME: ldap2.key
      LDAP_TLS_CA_CRT_FILENAME: snakeoil-ca-1.crt
      LDAP_TLS_VERIFY_CLIENT: "try"
    volumes:
      - ../../environment/ldap-authorizer-sasl-plain/ldap/custom:/container/service/slapd/assets/config/bootstrap/ldif/custom
      - ../../other/ldap-authorizer-with-ldap-failover/security:/container/service/slapd/assets/certs
    command: "--copy-service"
    networks:
      testing_net:
        ipv4_address: 172.28.1.3

  ldap3:
    image: osixia/openldap:1.3.0
    hostname: ldap3
    container_name: ldap3
    environment:
      LDAP_ORGANISATION: "Confluent"
      LDAP_DOMAIN: "confluent.io"
      LDAP_TLS_CRT_FILENAME: ldap3-ca1-signed.crt
      LDAP_TLS_KEY_FILENAME: ldap3.key
      LDAP_TLS_CA_CRT_FILENAME: snakeoil-ca-1.crt
      LDAP_TLS_VERIFY_CLIENT: "try"
    volumes:
      - ../../environment/ldap-authorizer-sasl-plain/ldap/custom:/container/service/slapd/assets/config/bootstrap/ldif/custom
      - ../../other/ldap-authorizer-with-ldap-failover/security:/container/service/slapd/assets/certs
    command: "--copy-service"
    networks:
      testing_net:
        ipv4_address: 172.28.1.4

  zookeeper:
    hostname: zookeeper.confluent.io
    networks:
      testing_net:
        ipv4_address: 172.28.1.5

  broker:
    hostname: broker.confluent.io
    # this is not working so workaround with /etc/resolv.conf
    dns: 172.28.1.1
    dns_search: confluent.io
    volumes:
      - ../../other/ldap-authorizer-with-ldap-failover/resolv.conf:/etc/resolv.conf
      - ../../other/ldap-authorizer-with-ldap-failover/security:/etc/kafka/security
    environment:
      # https://ldap.com/dns-srv-records-for-ldap/
      # LDAP provider URL
      KAFKA_LDAP_JAVA_NAMING_PROVIDER_URL: "ldaps:///dc=confluent,dc=io"
      KAFKA_LDAP_SSL_TRUSTSTORE_LOCATION: /etc/kafka/security/kafka.broker.truststore.jks
      KAFKA_LDAP_SSL_TRUSTSTORE_PASSWORD: confluent
      KAFKA_LDAP_JAVA_NAMING_SECURITY_PROTOCOL: SSL
      #KAFKA_LDAP_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
      KAFKA_LDAP_GROUP_SEARCH_BASE: ou=groups
      # KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf
      #             -Djavax.net.debug=all
    networks:
      testing_net:
        ipv4_address: 172.28.1.6

  schema-registry:
    hostname: schema-registry.confluent.io
    networks:
      testing_net:
        ipv4_address: 172.28.1.7


  connect:
    # this is not working so workaround with /etc/resolv.conf
    dns: 172.28.1.1
    dns_search: confluent.io
    volumes:
      - ../../other/ldap-authorizer-with-ldap-failover/resolv.conf:/etc/resolv.conf
    hostname: connect.confluent.io
    depends_on:
    - ldap
    - ldap2
    - ldap3
    - bind
    networks:
      testing_net:
        ipv4_address: 172.28.1.8

  control-center:
    hostname: control-center.confluent.io
    networks:
      testing_net:
        ipv4_address: 172.28.1.9

networks:
  default:
    name: confluent.io
  testing_net:
    ipam:
        driver: default
        config:
        - subnet: 172.28.0.0/16