version: '3.5'
services:

    bind:
        build:
            context: ../../other/ldap-authorizer-with-ldap-failover/bind
        hostname: bind.example.com
        container_name: bind
        ports:
        - 53:53/udp
        restart: unless-stopped
        depends_on:
        - ldap
        - ldap2
        - ldap3
        networks:
            testing_net:
                ipv4_address: 172.28.1.1

    ldap:
        hostname: ldap.example.com
        networks:
            testing_net:
                ipv4_address: 172.28.1.2


    zookeeper:
        hostname: zookeeper.example.com
        networks:
            testing_net:
                ipv4_address: 172.28.1.3


    schema-registry:
        hostname: schema-registry.example.com
        networks:
            testing_net:
                ipv4_address: 172.28.1.4


    control-center:
        hostname: control-center.example.com
        networks:
            testing_net:
                ipv4_address: 172.28.1.5


    connect:
        # this is not working so workaround with /etc/resolv.conf
        dns: 172.28.1.1
        dns_search: example.com
        volumes:
            - ../../other/ldap-authorizer-with-ldap-failover/resolv.conf:/etc/resolv.conf
        hostname: connect.example.com
        depends_on:
        - ldap
        - ldap2
        - ldap3
        - bind
        networks:
            testing_net:
                ipv4_address: 172.28.1.6

    ldap2:
        image: osixia/openldap:1.3.0
        hostname: ldap2.example.com
        container_name: ldap2
        environment:
            LDAP_ORGANISATION: "Confluent"
            LDAP_DOMAIN: "confluent.io"
        volumes:
            - ../../environment/ldap-authorizer-sasl-plain/ldap/custom:/container/service/slapd/assets/config/bootstrap/ldif/custom
        command: "--copy-service"
        networks:
            testing_net:
                ipv4_address: 172.28.1.7


    ldap3:
        image: osixia/openldap:1.3.0
        hostname: ldap3
        container_name: ldap3
        environment:
            LDAP_ORGANISATION: "Confluent"
            LDAP_DOMAIN: "confluent.io"
        volumes:
            - ../../environment/ldap-authorizer-sasl-plain/ldap/custom:/container/service/slapd/assets/config/bootstrap/ldif/custom
        command: "--copy-service"
        networks:
            testing_net:
                ipv4_address: 172.28.1.8


    broker:
        hostname: broker.example.com
        # this is not working so workaround with /etc/resolv.conf
        dns: 172.28.1.1
        dns_search: example.com
        volumes:
            - ../../other/ldap-authorizer-with-ldap-failover/resolv.conf:/etc/resolv.conf
        environment:
            # https://ldap.com/dns-srv-records-for-ldap/
            # LDAP provider URL
            KAFKA_LDAP_JAVA_NAMING_PROVIDER_URL: "ldap://example.com"
        networks:
            testing_net:
                ipv4_address: 172.28.1.9

networks:
  default:
    name: example.com
  testing_net:
    ipam:
      driver: default
      config:
          - subnet: 172.28.0.0/16