version: '3.5'
services:

    bind:
      build:
        context: ../../other/ldap-authorizer-with-ldap-failover/bind
      hostname: bind.example.com
      container_name: bind
      ports:
        - 53:53/udp
      restart: unless-stopped
      depends_on:
        - ldap
        - ldap2
        - ldap3

    ldap:
        hostname: ldap.example.com

    zookeeper:
        hostname: zookeeper.example.com

    schema-registry:
        hostname: schema-registry.example.com

    control-center:
        hostname: control-center.example.com

    connect:
        dns: bind.example.com
        hostname: connect.example.com

    ldap2:
        image: osixia/openldap:1.3.0
        hostname: ldap2.example.com
        container_name: ldap2
        environment:
            LDAP_ORGANISATION: "Confluent"
            LDAP_DOMAIN: "confluent.io"
        volumes:
            - ../../environment/ldap-authorizer-sasl-plain/ldap/custom:/container/service/slapd/assets/config/bootstrap/ldif/custom
        command: "--copy-service"

    ldap3:
        image: osixia/openldap:1.3.0
        hostname: ldap3
        container_name: ldap3
        environment:
            LDAP_ORGANISATION: "Confluent"
            LDAP_DOMAIN: "confluent.io"
        volumes:
            - ../../environment/ldap-authorizer-sasl-plain/ldap/custom:/container/service/slapd/assets/config/bootstrap/ldif/custom
        command: "--copy-service"

    broker:
        hostname: broker.example.com
        dns: bind.example.com
        environment:
            # https://ldap.com/dns-srv-records-for-ldap/
            # LDAP provider URL
            KAFKA_LDAP_JAVA_NAMING_PROVIDER_URL: "ldap://ldap.example.com:389/DC=CONFLUENT,DC=IO"

networks:
  default:
    name: example.com