---
version: '3.5'
services:
  broker-europe:
      volumes:
        - ../../multi-data-center/cluster-linking/sasl-plain-acl/europe-client.properties:/tmp/europe-client.properties
        - ../../multi-data-center/cluster-linking/sasl-plain-acl/us-client.properties:/tmp/us-client.properties
        - ../../multi-data-center/cluster-linking/sasl-plain-acl/superuser-client.properties:/tmp/superuser-client.properties
        - ../../multi-data-center/cluster-linking/sasl-plain-acl/source.config:/tmp/source.config
        - ../../multi-data-center/cluster-linking/sasl-plain-acl/kafka-europe.jaas.conf:/etc/kafka/kafka_server_jaas.conf
      environment:
        KAFKA_CONFLUENT_CLUSTER_LINK_ENABLE : "true"
        # required otherwise getting Error while executing cluster link command: org.apache.kafka.common.errors.InvalidConfigurationException: password.encoder.secret must be configured for cluster linking with sensitive or custom configs
        KAFKA_PASSWORD_ENCODER_SECRET: frankBGdu39
        # set ACLs
        KAFKA_AUTHORIZER_CLASS_NAME: $KAFKA_AUTHORIZER_CLASS_NAME
        KAFKA_ZOOKEEPER_SET_ACL: "true"
        KAFKA_LOG4J_LOGGERS: "kafka.authorizer.logger=INFO"
        KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "false"
        KAFKA_SUPER_USERS: User:broker;User:schemaregistry;User:client;User:connect

  broker-us:
      volumes:
        - ../../multi-data-center/cluster-linking/sasl-plain-acl/kafka-us.jaas.conf:/etc/kafka/kafka_server_jaas.conf
      environment:
        # set ACLs
        KAFKA_AUTHORIZER_CLASS_NAME: $KAFKA_AUTHORIZER_CLASS_NAME
        KAFKA_ZOOKEEPER_SET_ACL: "true"
        KAFKA_LOG4J_LOGGERS: "kafka.authorizer.logger=INFO"
        KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "false"
        KAFKA_SUPER_USERS: User:broker;User:schemaregistry;User:client;User:connect