name: Update README

on:
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          repository: vdesabou/kafka-docker-playground
          fetch-depth: 0

      - name: Decrypt secrets.tar
        run: |
          ./.github/scripts/decrypt_secret.sh
          tar xvf secrets.tar
          rm secrets.tar
          mkdir -p $HOME/.aws
          mv aws_config $HOME/.aws/config
          mv aws_credentials $HOME/.aws/credentials
          mv aws_credentials_with_assuming_iam_role $HOME/.aws/credentials-with-assuming-iam-role
          chmod -R a+rw $HOME/.aws
          mkdir -p $HOME/.confluent
          mv config.cc.travis $HOME/.confluent/config
          source secrets.properties > /dev/null 2>&1
          echo "$DOCKER_PASSWORD" | docker login -u vdesabou --password-stdin
        env:
          SECRETS_ENCRYPTION_PASSWORD: ${{ secrets.SECRETS_ENCRYPTION_PASSWORD }}

      - name: Update README
        run: |
          ./scripts/update-readme.sh "5.3.6 5.4.5 5.5.6 6.0.5 6.1.3 6.2.2 7.0.0"
      - name: push
        uses: github-actions-x/commit@v2.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'master'
          commit-message: 'updating with latest versions'
          files: ./README.md ./docs/content.md ./docs/introduction.md
          name: Vincent de Saboulin
